### ISSUE TITLE
Fp\Json\jsonDecode is unsafe

### ISSUE THREAD

**Issue by klimick** [whsv26/functional#6]
If you run the following piece of code, it will lead to a runtime error:

```php
<?php

use Fp\Functional\Either\Right;
use Fp\Functional\Either\Left;
use function Fp\Json\jsonDecode;

require __DIR__ . '/vendor/autoload.php';

$decoded = jsonDecode('"kek"')
    ->map(fn(array $val) => array_merge($val, ['lol' => '_']));


```

```
PHP Fatal error:  Uncaught TypeError: {closure}(): Argument #1 ($val) must be of type array, string given, called in /home/php/whsv26/functional/src/Fp/Functional/Either/Either.php on line 83 and defined in /home/php/whsv26/functional/run.php:12
Stack trace:
#0 /home/php/whsv26/functional/src/Fp/Functional/Either/Either.php(83): {closure}()
#1 /home/php/whsv26/functional/run.php(15): Fp\Functional\Either\Either->flatMap()
#2 {main}
  thrown in /home/php/whsv26/functional/run.php on line 12

```
Because `json_decode` can deserialize literals like numbers, strings, booleans.

**Comment by whsv26** [comment]
Now it's Either<string, array|scalar>
